notifications:
  email: false
  slack: false

matrix:
  include:
    - language: php
      php: 7.1

      before_install:
        - cp ./env_testing ./.env

      before_script:
        - composer install --dev --prefer-source --no-interaction

      script:
        - ./vendor/bin/phpcs --standard=PSR2 --extensions=php ./app ./tests
        - ./vendor/bin/phpstan analyse tests/Unit tests/Feature app/Http/Controllers/*Controller.php --level=1
        - ./vendor/phpunit/phpunit/phpunit tests/Unit/*
        - nohup php -S localhost:8000 -t public/ </dev/null &>/dev/null &
        - PHP_SERVER_PID=$!
        - ./vendor/bin/phpunit tests/Feature/*
        - kill -9 $PHP_SERVER_PID

    - language: node_js
      node_js: "node"
      before_script:
        - npm install -g stylelint
      script:
        - yarn prod
        - yarn js:test:eslint
        - yarn scss:test:stylelint
        - yarn js:test:prod

deploy:
  provider: script
  script: ./deploy.sh
  on:
    branch: master